#!/usr/bin/env python3
# Generates secp256k1_g_odd_w12.inc and secp256k1_phig_odd_w12.inc: the odd multiples (2j+1)*G
# and (2j+1)*phi(G), j = 0..1023, in affine coordinates, for the width-12 NAF of the G half of
# the batched signer recovery (AIRBENDER). phi(x, y) = (BETA*x, y) = LAMBDA*(x, y).
P = 2**256 - 2**32 - 977
GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
BETA = 0x7AE96A2B657C07106E64479EAC3434E99CF0497512F58995C1396C28719501EE
LAMBDA = 0x5363AD4CC05C30E0A5261C028812645A122E22EA20816678DF02967C1B23BD72


def add(p, q):
    if p is None:
        return q
    if q is None:
        return p
    (x1, y1), (x2, y2) = p, q
    if x1 == x2:
        if (y1 + y2) % P == 0:
            return None
        lam = 3 * x1 * x1 * pow(2 * y1, -1, P) % P
    else:
        lam = (y2 - y1) * pow(x2 - x1, -1, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return x3, (lam * (x1 - x3) - y1) % P


def mul(k, p):
    r = None
    while k:
        if k & 1:
            r = add(r, p)
        p = add(p, p)
        k >>= 1
    return r


def emit(path, points, title):
    with open(path, "w") as f:
        f.write(f"// {title}\n")
        f.write("// Generated by secp256k1_odd_tables.py: (2j+1)*P for j = 0..1023, affine.\n")
        for x, y in points:
            assert (y * y - x * x * x - 7) % P == 0
            f.write(f"    {{0x{x:064x}_u256, 0x{y:064x}_u256}},\n")


g = (GX, GY)
g2 = add(g, g)
odd = [g]
for _ in range(1023):
    odd.append(add(odd[-1], g2))
phi = [(BETA * x % P, y) for x, y in odd]
assert mul(LAMBDA, g) == phi[0]
emit("secp256k1_g_odd_w12.inc", odd,
     "1024 odd multiples of G for the width-12 NAF of the batched recovery")
emit("secp256k1_phig_odd_w12.inc", phi,
     "1024 odd multiples of phi(G) for the width-12 NAF of the batched recovery")
